### ISSUE TITLE
Add existing Quests as Subquest

### ISSUE THREAD

**Issue by zarazandra** [typhonjs-fvtt/typhonjs-quest-log#161] opened 2023-07-26 11:51 UTC
Hi, 

I learned the hard way, that you can't mark a quest as a subquest to another Quest. You have to write it all again from scratch via the parental Quest ->  organize quest -> add subquest (may not be the original words from the button, since I use it in german). 

Can you please simplify that by adding the ability to drag quests into the subquest-zone or the goals? Or maybe an "add existing"-Button? Something? I would reeeally appreciate it. 

Thanks in Advance!

**Comment by typhonrt** [comment] 2023-07-26 12:19
Hi @zarazandra. Thanks for filing an enhancement issue. This is a duplicate of #29, so I'll close this one. 

Likely in the spring of '24 I'll be running a crowd funding campaign to cover a 5 month full time development cycle to massively update the quest log and complete all of the outstanding issues. Until then you'll have to enter the quest data that you'd like to move to a sub-quest manually.

**Closed by typhonrt** 2023-07-26 12:19 UTC
Labels: enhancement
